[package]
name = "birth-stone"
version = "0.1.0"
authors = ["dkyun"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "birth_stone"
crate-type = ["staticlib"]

[dependencies]
cty = "0.2.1"